### PR TITLE
[DEV-1148, DEV-1190, DEV-1194]: auth fixes and translations

### PR DESCRIPTION
**Pull request by MikeAtUqido**
#### List of Changes

* Fixes on the auth pages
* Moved the translations from the `translations.ts` file to new json files used by `next-intl`

#### Motivation and Context

The auth pages had some bugs and we updated the i18n of the app

#### How Has This Been Tested?

- [x] Manually

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kin0992** [comment]
@MikeAtUqido please make separate PRs.

just a couple of reason why you should do that:
- smaller the PR is, faster the review will be
- a fast review produce a fast deploy
- we cannot wait to fix some copy (e.g. https://pagopa.atlassian.net/browse/DEV-1190) before fixing some more important bug of functionality (e.g. https://pagopa.atlassian.net/browse/DEV-1129)

**Comment by MikeAtUqido** [comment]
> @MikeAtUqido please make separate PRs.
> 
> just a couple of reason why you should do that:
> 
> * smaller the PR is, faster the review will be
> * a fast review produce a fast deploy
> * we cannot wait to fix some copy (e.g. https://pagopa.atlassian.net/browse/DEV-1190) before fixing some more important bug of functionality (e.g. https://pagopa.atlassian.net/browse/DEV-1129)

@kin0992 I did, in fact, another PR for the bug you mentioned (https://github.com/pagopa/developer-portal/pull/454) but the since other changes was done in the meantime at the same files merging them in that PR became really difficult, I included those changes in this PR for the exact reason, they changes the same files and would be difficult to work on them at the same time.

The other reason I included those changes in this PR is that the tickets [DEV-1128](https://pagopa.atlassian.net/browse/DEV-1128), [DEV-1129](https://pagopa.atlassian.net/browse/DEV-1129), [DEV-1148](https://pagopa.atlassian.net/browse/DEV-1148) are the same bug which is included in the [DEV-1190](https://pagopa.atlassian.net/browse/DEV-1190) ticket. So they seem 4 different tickets, but in reality they are one.

Does it make sense?

**Comment by kin0992** [comment]
> > @MikeAtUqido please make separate PRs.
> > just a couple of reason why you should do that:
> > 
> > * smaller the PR is, faster the review will be
> > * a fast review produce a fast deploy
> > * we cannot wait to fix some copy (e.g. https://pagopa.atlassian.net/browse/DEV-1190) before fixing some more important bug of functionality (e.g. https://pagopa.atlassian.net/browse/DEV-1129)
> 
> @kin0992 I did, in fact, another PR for the bug you mentioned (#454) but the since other changes was done in the meantime at the same files merging them in that PR became really difficult, I included those changes in this PR for the exact reason, they changes the same files and would be difficult to work on them at the same time.
> 
> The other reason I included those changes in this PR is that the tickets [DEV-1128](https://pagopa.atlassian.net/browse/DEV-1128), [DEV-1129](https://pagopa.atlassian.net/browse/DEV-1129), [DEV-1148](https://pagopa.atlassian.net/browse/DEV-1148) are the same bug which is included in the [DEV-1190](https://pagopa.atlassian.net/browse/DEV-1190) ticket. So they seem 4 different tickets, but in reality they are one.
> 
> Does it make sense?

@MikeAtUqido I get your point, still I don't think all those Jira activities are the same bug: IMHO there is a ticket that say to enable users to request a new OTP (for authentication), which is a new functionality; a ticket says to show an error to a user and the error should suggest to request a new OTP; a ticket says to change the copy.
I think these tickets should be in separate PR. Moreover, if we have different tickets that are expressing the same issue, I'd Abbandon one linking it to its clone, adding the relationship on Jira, so that we remove the entropy we don't need 😄

**Comment by MikeAtUqido** [comment]
Closing in favor of #484 and #486

**Pull request closed without merging**
